package io.craigmiller160.authserver.exception

class AccessNotFoundException(msg: String, cause: Throwable? = null) : RuntimeException(msg, cause)
